name: Build and test client and server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-client:
    name: client-build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: client/package-lock.json

    - name: Build the client
      run: npm run build

  build-server:
    name: client-server
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server
    
    env:
      JWT_SECRET : ${{secrets.JWT_SECRET}}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: server/package-lock.json

    - name: test the server
      run: npm run test
    - name: build the server
      run: npm run build
